# Generated by Django 5.2.1 on 2025-05-13 05:39

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=board.models.get_today),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=board.models.get_today),
        ),
    ]
